title: Almir Sarajčić
email: TB_Almir@hotmail.com
description: 'Full stack web developer proficient with Ruby on Rails, PHP and Javascript'
keywords: 'developer, web, development, rails, ruby, ruby on rails, php, javascript, sql, laravel, jquery, kohana, git'
url: ''
baseurl: ''
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-assets
  - jekyll-sitemap
markdown: kramdown
highlighter: rouge
assets:
  baseurl: /assets/
  sources:
    - _assets/pdf
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendors/jquery-rails/vendor/assets/javascripts
    - _vendors/Font-Awesome/css
    - _vendors/Font-Awesome/fonts
    - _vendors/bootstrap/dist/css
    - _vendors/jsonresume-theme-elegant/assets/css
  js_compressor: uglifier
  css_compressor: sass
  gzip: false
  debug: false
